Pages:
  - changed-files:
      - any-glob-to-any-file: app/**/*

Components:
  - changed-files:
      - any-glob-to-any-file: components/**/*

Utils:
  - changed-files:
      - any-glob-to-any-file: utils/**/*

Config:
  - changed-files:
      - any-glob-to-any-file: ['next.config.js', 'tsconfig.json', 'next-env.d.ts']

Dependencies:
  - changed-files:
      - any-glob-to-any-file: ['**/yarn.lock']
