name: Lint

on:
  pull_request:
    branches: ['master']

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Setup node 🏗
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Install dependencies 👨🏻‍💻
        run: yarn

      - name: Build packages 🏘️
        run: yarn build

      - name: Run linter 👀
        run: yarn lint
